/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MiragePageCreator } from "./MiragePageCreator";
export type { PageCreator } from "./PageCreator";
